name: flutter_melos_monorepo

packages:
  - apps/*
  - packages/*

scripts:
  postbootstrap: dart pub get

  analyze:
    exec: flutter analyze .
    description: Analyze all packages

  format:
    exec: dart format .
    description: Format all packages

  test:
    exec: flutter test
    packageFilters:
      dirExists:
        - test

  build:example_ios:
    run: |
      cd apps/example_app
      flutter build ios --no-codesign
    description: Build iOS for example_app

  build:framework:
    run: |
      cd apps/integration_module
      flutter build ios-framework --output=../../build/ios_frameworks --no-profile
    description: Build XCFrameworks from integration_module

  build:aar:
    run: |
      cd apps/integration_module
      flutter build aar --no-profile --no-debug
    description: Build Android AAR from integration_module
